name: CMake on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        compiler: [clang, gcc]
        include:
          - compiler: clang
            c_compiler: clang
            cpp_compiler: clang++
          - compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libx11-dev \
          libxkbcommon-dev \
          libxcb-keysyms1-dev \
          libvulkan-dev \
          vulkan-tools \
          libglfw3-dev \
          libglew-dev \
          libglm-dev \
          libsdl2-dev \
          libsdl2-mixer-dev \
          portaudio19-dev \
          libentt-dev \
          libgtest-dev \
          libgoogle-glog-dev \
          freeglut3-dev \
          mesa-common-dev \
          libglu1-mesa-dev

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -G Ninja

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        cd build
        ctest --output-on-failure
